/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WALK = 5;
  /** RegularExpression Id. */
  int JUMP = 6;
  /** RegularExpression Id. */
  int JUMPTO = 7;
  /** RegularExpression Id. */
  int VEER = 8;
  /** RegularExpression Id. */
  int LOOK = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int GRAB = 11;
  /** RegularExpression Id. */
  int GET = 12;
  /** RegularExpression Id. */
  int FREE = 13;
  /** RegularExpression Id. */
  int POP = 14;
  /** RegularExpression Id. */
  int AROUND = 15;
  /** RegularExpression Id. */
  int LEFT = 16;
  /** RegularExpression Id. */
  int RIGHT = 17;
  /** RegularExpression Id. */
  int NORTH = 18;
  /** RegularExpression Id. */
  int SOUTH = 19;
  /** RegularExpression Id. */
  int EAST = 20;
  /** RegularExpression Id. */
  int WEST = 21;
  /** RegularExpression Id. */
  int FRONT = 22;
  /** RegularExpression Id. */
  int BACK = 23;
  /** RegularExpression Id. */
  int ISFACING = 24;
  /** RegularExpression Id. */
  int ISVALID = 25;
  /** RegularExpression Id. */
  int CANWALK = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int PROG = 28;
  /** RegularExpression Id. */
  int GORP = 29;
  /** RegularExpression Id. */
  int PROC = 30;
  /** RegularExpression Id. */
  int CORP = 31;
  /** RegularExpression Id. */
  int VAR = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int FI = 36;
  /** RegularExpression Id. */
  int DO = 37;
  /** RegularExpression Id. */
  int OD = 38;
  /** RegularExpression Id. */
  int REPEAT = 39;
  /** RegularExpression Id. */
  int PER = 40;
  /** RegularExpression Id. */
  int PICK = 41;
  /** RegularExpression Id. */
  int CONSTANT = 42;
  /** RegularExpression Id. */
  int WORD = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int LMINUS = 45;
  /** RegularExpression Id. */
  int LMAYUS = 46;
  /** RegularExpression Id. */
  int ASSIGNMENT = 47;
  /** RegularExpression Id. */
  int PI = 48;
  /** RegularExpression Id. */
  int PD = 49;
  /** RegularExpression Id. */
  int CBL = 50;
  /** RegularExpression Id. */
  int CBR = 51;
  /** RegularExpression Id. */
  int SC = 52;
  /** RegularExpression Id. */
  int CM = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"walk\"",
    "\"jump\"",
    "\"jumpTo\"",
    "\"veer\"",
    "\"look\"",
    "\"drop\"",
    "\"grab\"",
    "\"get\"",
    "\"free\"",
    "\"pop\"",
    "\"around\"",
    "\"left\"",
    "\"right\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"front\"",
    "\"back\"",
    "\"isfacing\"",
    "\"isValid\"",
    "\"canWalk\"",
    "\"not\"",
    "\"PROG\"",
    "\"GORP\"",
    "\"PROC\"",
    "\"CORP\"",
    "\"VAR\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"fi\"",
    "\"do\"",
    "\"od\"",
    "\"repeatTimes\"",
    "\"per\"",
    "\"pick\"",
    "<CONSTANT>",
    "<WORD>",
    "<DIGIT>",
    "<LMINUS>",
    "<LMAYUS>",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
  };

}
